"""
Generalise the on and off-policy Bitter LLM by simply allowing for the gate samples to be passed in as an argument.

This will allow us to use the same code for both on- and off-policy training (the off-policy is not dependent on the samples).

Also: compatible with the new Gemma2 model implementation in transformers.
"""
import os
import json
from copy import deepcopy
import time
import numpy as np
import pandas as pd

from torch import nn
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torch.profiler import record_function

# TODO: migrate some things from bitter_llm.py to utils.py
from .utils import display_gpu_memory, display_gating, count_parameters, lookup_gpu_TFLOPS
from .modules import LinearGater, RandomGater, EquidistantGater, AverageTokenDownsampler, get_merge_dst, create_gemma2DecoderLayer, discounted_rewards_torch
from .conditional_sequential import SequentiallyDependentRandomGater
from transformers.models.gemma2.modeling_gemma2 import Gemma2Model, Gemma2Config, Gemma2RotaryEmbedding, HybridCache, StaticCache, Cache
from .downsample_rate_scheduler import DefaultDownsampleRateScheduler

from typing import Optional, Dict, Union, List


independent_gater_classes = {LinearGater, RandomGater, EquidistantGater}

class IndependentWrapperGater(nn.Module):
    def __init__(self, gater: nn.Module):
        super().__init__()
        self.gater = gater

    def forward(self, x: torch.Tensor, downsample_rate=None) -> torch.Tensor:

        if downsample_rate is not None:
            raise NotImplementedError(f"passed downsample_rate is not implemented for {self.__class__=}")

        # Sample gating binary variables for each token.
        gate_logits, gate_probs = self.gater(x)

        # Sample from the gate_probs independently for each token.
        gate_samples = torch.bernoulli(gate_probs)

        return gate_logits, gate_probs, gate_samples


class ExactRandomGater(nn.Module):
    """
    This gater samples from the distribution generated by resampling b_1 ... b_{4096} iid bernoulli until exactly 1024 of them are 1. 
    This is the similar to RandomGater, but with some serial dependency that makes it more GPU-efficient and reliable.
    """

    def __init__(self, embedding_dim: int, downsample_rate: float):
        super().__init__()
        self.embedding_dim = embedding_dim
        self.downsample_rate = downsample_rate

    def forward(self, x: torch.Tensor, downsample_rate=None) -> torch.Tensor:
        batch_size, seq_len, _ = x.shape

        if downsample_rate is None:
            downsample_rate = self.downsample_rate

        num_ones = round(seq_len * downsample_rate)

        # Generate random values for each position
        latents = torch.rand(batch_size, seq_len, 1, device=x.device)

        # Set the first and last tokens to infinity to ensure it is selected.
        latents[:, 0] = torch.tensor(float('inf'), dtype=latents.dtype, device=x.device)
        latents[:, -1] = torch.tensor(float('inf'), dtype=latents.dtype, device=x.device)

        # Use topk to find the indices of the k largest values
        # This gives us exactly num_ones indices per batch
        _, top_indices = torch.topk(latents, k=num_ones, dim=1)
        gate_samples = torch.zeros(batch_size, seq_len, 1, dtype=x.dtype, device=x.device)
        gate_samples.scatter_(1, top_indices, 1)

        gate_probs = torch.ones(batch_size, seq_len, 1, dtype=x.dtype, device=x.device) * downsample_rate
        gate_logits = torch.log(gate_probs / (1 - gate_probs))
        return gate_logits, gate_probs, gate_samples


class SelectTokenDownsampler(nn.Module):
    def forward(self, x: torch.Tensor, position_ids: torch.Tensor, gate_samples: torch.Tensor) -> torch.Tensor:
        """
        Selects the tokens where the gate is 1. accordnig to:
        1 2 3 4 5
        1 0 0 1 1
        ->
        1 4 5
        inputs:
        x.shape = (batch_size, seq_len, embedding_dim)
        position_ids.shape = (batch_size, seq_len)
        gate_samples.shape = (batch_size, seq_len)
        returns:
        x_downsampled.shape = (batch_size, n_dst, embedding_dim)
        position_ids_downsampled.shape = (batch_size, n_dst)
        """

        batch_size, _, embedding_dim = x.shape
        down_merge_dst, n_dst = get_merge_dst(gate_samples)

        # Merge the tokens into the next token where the gate is 1.)
        max_n_dst = n_dst.max().item()

        # Also merge the position ids.
        position_ids_downsampled = torch.zeros(batch_size, max_n_dst, dtype=position_ids.dtype).to(x.device)
        position_ids_downsampled = torch.scatter_reduce(position_ids_downsampled, dim=1, index=down_merge_dst, src=position_ids, reduce="max", include_self=False)

        # Merge the downsampled tokens.
        # Use the trick: 1 2 3 4 5 * 1 0 0 1 1 = 1 0 0 4 5 which can then be reduced by sum.
        x = x * gate_samples.unsqueeze(-1)
        down_merge_dst = down_merge_dst.unsqueeze(-1).expand(-1, -1, embedding_dim)
        x_downsampled = torch.zeros(batch_size, max_n_dst, embedding_dim, dtype=x.dtype).to(x.device)
        x_downsampled = torch.scatter_reduce(x_downsampled, dim=1, index=down_merge_dst, src=x, reduce="sum", include_self=False)

        return x_downsampled, position_ids_downsampled, down_merge_dst


class DistributeTokenUpsampler(nn.Module):
    def forward(self, x: torch.Tensor, gate_samples: torch.Tensor) -> torch.Tensor:
        """
        Distributes the values of x to the next token where the gate is 1.
        1 2 3
        1 0 0 1 1
        ->
        1 1 1 2 3
        """
        batch_size, _, embedding_dim = x.shape
        # Upsample by removing the first token merge group, shifting all token groups down and adding another one token group at the end.
        up_gate_samples = gate_samples[:, 1:]
        up_gate_samples = torch.cat([up_gate_samples, torch.ones(batch_size, 1, dtype=up_gate_samples.dtype).to(up_gate_samples.device)], dim=1)
        up_merge_dst, _ = get_merge_dst(up_gate_samples)
        up_merge_dst = up_merge_dst.unsqueeze(-1).expand(-1, -1, embedding_dim)

        x_upsampled = torch.gather(x, dim=1, index=up_merge_dst)

        return x_upsampled, up_merge_dst


def gate_first_and_last_tokens(gate_samples: torch.Tensor, gate_probs: torch.Tensor, gate_logits: torch.Tensor) -> torch.Tensor:
    """
    Manually sets the first and last gate samples of the sequence to 1. Appropriately adjusts the gate_probs and gate_logits and detaches these parts from the computation graph.
    This is in theory unnecessary, but in practice it makes up/downsampling easier to implement.
    """
    batch_size, _, _ = gate_samples.shape
    gate_samples[:, 0] = 1.
    gate_samples[:, -1] = 1.
    ones = torch.ones(batch_size, 1, 1, dtype=gate_probs.dtype).to(gate_probs.device)
    # We need to also set the corresponding logits to 100. to avoid the gradient exploding based on this.
    gate_probs = torch.cat([ones, gate_probs[:, 1:-1], ones], dim=1)
    gate_logits = torch.cat([100*ones, gate_logits[:, 1:-1], 100*ones], dim=1)
    return gate_samples, gate_probs, gate_logits


def get_merge_dst(gate_samples: torch.Tensor) -> torch.Tensor:
    """
    Returns (merge_dst, dst_idx) the merge destination for each token in the sequence and the number of unique merge destinations.
    Input is a tensor of shape (batch_size, sequence_length) with 0 tokens are merged into the next 1 token.
    mapping:
    1 0 1 1 0 1 1 0 0 0 1
    |   | |   | |       |
    0 1 1 2 3 3 4 5 5 5 5
    """
    # "cycle" the gate samples, appending a zero to the beginning of each batch and ignoring the last gate.
    preceding_gate_samples = torch.cat([torch.zeros_like(gate_samples[:, -1]).unsqueeze(1), gate_samples[:, :-1]], dim=1).to(dtype=torch.long)
    # Trick: use cumsum to do this in a vectorized way.
    merge_dst = preceding_gate_samples.cumsum(dim=1)
    n_dst = merge_dst[:, -1] + 1 # The number of unique merge destinations is the last token's merge destination + 1.
    return merge_dst, n_dst


class AverageTokenDownsampler(nn.Module):
    def forward(self, x: torch.Tensor, position_ids: torch.Tensor, down_gate_samples: torch.Tensor) -> torch.Tensor:
        """
        1 2 3 4 5
        1 0 0 1 1
        ->
        1 3 5
        inputs:
        x.shape = (batch_size, seq_len, embedding_dim)
        position_ids.shape = (batch_size, seq_len)
        down_gate_samples.shape = (batch_size, seq_len)
        returns:
        x_downsampled.shape = (batch_size, n_dst, embedding_dim)
        position_ids_downsampled.shape = (batch_size, n_dst)

        Warning: this is nondeterministic due to race conditions in scatter_reduce and rounding errors.
        """
        batch_size, _, embedding_dim = x.shape
        down_merge_dst, n_dst = get_merge_dst(down_gate_samples)

        # Merge the tokens into the next token where the gate is 1.)
        max_n_dst = n_dst.max().item()

        # Also merge the position ids.
        position_ids_downsampled = torch.zeros(batch_size, max_n_dst, dtype=position_ids.dtype).to(x.device)
        position_ids_downsampled = torch.scatter_reduce(position_ids_downsampled, dim=1, index=down_merge_dst, src=position_ids, reduce="mean", include_self=False)

        # Merge the downsampled tokens.
        down_merge_dst = down_merge_dst.unsqueeze(-1).expand(-1, -1, embedding_dim)

        x_downsampled = torch.zeros(batch_size, max_n_dst, embedding_dim, dtype=x.dtype).to(x.device)
        x_downsampled = torch.scatter_reduce(x_downsampled, dim=1, index=down_merge_dst, src=x, reduce="mean", include_self=False)

        return x_downsampled, position_ids_downsampled, down_merge_dst


class FlexibleCache(Cache):
    def __init__(
        self,
        config,
        max_batch_size: int,
        max_cache_len: Optional[int] = None,
        device: Union[torch.device, str, None] = None,
        dtype: torch.dtype = torch.float32,
        layer_device_map: Optional[Dict[int, Union[str, torch.device, int]]] = None,
    ) -> None:
        super().__init__()
        if not hasattr(config, "sliding_window") or config.sliding_window is None:
            raise ValueError(
                "Setting `cache_implementation` to 'sliding_window' requires the model config supporting "
                "sliding window attention, please check if there is a `sliding_window` field in the model "
                "config and it's not set to None."
            )
        self.max_cache_len = max_cache_len
        self.max_batch_size = max_batch_size
        # Some model define a custom `head_dim` != config.hidden_size // config.num_attention_heads
        self.head_dim = (
            config.head_dim if hasattr(config, "head_dim") else config.hidden_size // config.num_attention_heads
        )

        self._dtype = dtype
        self.num_key_value_heads = (
            config.num_attention_heads if config.num_key_value_heads is None else config.num_key_value_heads
        )

        # This is the only line we change from the original implementation.
        self.is_sliding = torch.tensor(
            [True] * config.n_down_layers + [False] * config.n_mid_layers + [True] * config.n_up_layers, dtype=torch.bool
        )

        self.key_cache: List[torch.Tensor] = []
        self.value_cache: List[torch.Tensor] = []
        global_cache_shape = (self.max_batch_size, self.num_key_value_heads, max_cache_len, self.head_dim)
        sliding_cache_shape = (
            self.max_batch_size,
            self.num_key_value_heads,
            min(config.sliding_window, max_cache_len),
            self.head_dim,
        )
        device = torch.device(device) if device is not None and isinstance(device, str) else None
        for i in range(config.num_hidden_layers):
            if layer_device_map is not None:
                layer_device = layer_device_map[i]
            else:
                layer_device = device
            # Note: `mark_static_address` is used to tag the cache as an fixed data pointer, preventing cuda graph
            # breaks when updating the cache.
            cache_shape = global_cache_shape if not self.is_sliding[i] else sliding_cache_shape
            new_layer_key_cache = torch.zeros(cache_shape, dtype=self._dtype, device=layer_device)
            new_layer_value_cache = torch.zeros(cache_shape, dtype=self._dtype, device=layer_device)
            torch._dynamo.mark_static_address(new_layer_key_cache)
            torch._dynamo.mark_static_address(new_layer_value_cache)
            self.key_cache.append(new_layer_key_cache)
            self.value_cache.append(new_layer_value_cache)


    def update(self, *args, **kwargs):
        return HybridCache.update(self, *args, **kwargs)
    
    def _sliding_update(self, *args, **kwargs):
        return HybridCache._sliding_update(self, *args, **kwargs)
    
    def _static_update(self, *args, **kwargs):
        return HybridCache._static_update(self, *args, **kwargs)
    
    def get_max_cache_shape(self) -> Optional[int]:
        return HybridCache.get_max_cache_shape(self)

    def get_seq_length(self, layer_idx: Optional[int] = 0):
        return HybridCache.get_seq_length(self, layer_idx)

    def reset(self):
        return HybridCache.reset(self)


# Copied from Gemma2Model, used to create the causal mask.
@torch.no_grad()
def _update_causal_mask(
    attention_mask: torch.Tensor,
    input_tensor: torch.Tensor,
    cache_position: torch.Tensor,
    past_key_values: HybridCache,
    attn_implementation: str,
):
    # Flash Attention currently doesn't support static cache but Gemma2 work only with static cache.
    # So we will pass in attention mask as is in any case, not only when ther's padding. Then we'll use its shape
    # to cut out keys/values trailing 0 used in static cache. This workaround should be compile compatible
    # as it doesn't cause dynamic control issues.
    if attn_implementation == "flash_attention_2":
        return attention_mask # FlashAttention2 handles the causal mask internally.

    dtype, device = input_tensor.dtype, input_tensor.device
    sequence_length = input_tensor.shape[1]
    if isinstance(past_key_values, (HybridCache, StaticCache, FlexibleCache)):
        target_length = past_key_values.get_max_cache_shape()
    else:
        target_length = attention_mask.shape[-1] if attention_mask is not None else input_tensor.shape[1]

    # In case the provided `attention` mask is 2D, we generate a causal mask here (4D).
    causal_mask = Gemma2Model._prepare_4d_causal_attention_mask_with_cache_position(
        attention_mask,
        sequence_length=sequence_length,
        target_length=target_length,
        dtype=dtype,
        device=device,
        cache_position=cache_position,
        batch_size=input_tensor.shape[0],
    )
    return causal_mask


def get_gemma2_attention_mask(input_tensor, cache_position, past_key_value, attn_implementation):
    
    if cache_position is None:
        _, seq_len, _ = input_tensor.shape
        cache_position = torch.arange(seq_len, dtype=torch.long, device=input_tensor.device)

    attention_mask = _update_causal_mask(
        attention_mask=None,
        input_tensor=input_tensor,
        cache_position=cache_position,
        past_key_values=past_key_value,
        attn_implementation=attn_implementation,
    )

    return cache_position, attention_mask


class DownsampleRateEmbedding(nn.Module):
    def __init__(self, embedding_dim: int, hidden_dim: int = 32):
        super().__init__()

        self.backbone = nn.Sequential(
            nn.Linear(1, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, embedding_dim),
        )


    def forward(self, downsample_rate: float, dtype, device):
        """
        returns the downsample rate.
        """

        downsample_rate = torch.tensor(downsample_rate, dtype=dtype, device=device).unsqueeze(0)
        embedding = self.backbone(downsample_rate)
        embedding = embedding.reshape(1, 1, -1) # to broadcast over the batch and sequence dimensions.

        return embedding


class FlexibleBitterLLM(nn.Module):
    # Use Gemma2DecoderLayer as a drop in replacement for the TransformerEncoderLayer, with RoPE and sliding window pre-implemented.
    # Also uses a causal mask.
    def __init__(
        self, 
        vocab_size: int,
        embedding_dim: int, 
        num_heads: int, 
        downsample_rate: float = 0.25, 
        sliding_window = 64, 
        down_layer_gate=None,
        GaterClass=LinearGater, 
        DownSamplerClass=AverageTokenDownsampler, 
        UpsamplerClass=DistributeTokenUpsampler, 
        DownsampleRateEmbeddingClass=None,
        separate_early_output=True, 
        n_down_layers=2, 
        n_mid_layers=6, 
        n_up_layers=2, 
        flash_attn=True, 
        compile=False
    ):
        super().__init__()
        self.embedding_dim = embedding_dim
        self.embedding = nn.Embedding(vocab_size, embedding_dim)

        head_dim = embedding_dim // num_heads

        self._attn_implementation = "flash_attention_2" if flash_attn else "eager"
        print(f"using {self._attn_implementation=}")

        self.byte_layer_config = Gemma2Config(
            head_dim=head_dim,
            query_pre_attn_scalar=head_dim, 
            sliding_window=sliding_window,
            intermediate_size=embedding_dim,
            hidden_size=embedding_dim,
            num_attention_heads=num_heads,
            num_key_value_heads=num_heads,
            attn_implementation=self._attn_implementation
        )

        self.deep_layer_config = Gemma2Config(
            head_dim=head_dim,
            query_pre_attn_scalar=head_dim, 
            sliding_window=None,
            intermediate_size=embedding_dim * 4, # dim_feedforward should scale inversely with the number of tokens in the sequence.
            hidden_size=embedding_dim,
            num_attention_heads=num_heads,
            num_key_value_heads=num_heads,
            attn_implementation=self._attn_implementation
        )

        # Layer idx=0 is necessary for the sliding window to be applied.
        self.down_layers = nn.ModuleList([
            create_gemma2DecoderLayer(self.byte_layer_config, layer_idx=i, compile=compile) for i in range(n_down_layers)
        ])

        self.mid_layers = nn.ModuleList([
            create_gemma2DecoderLayer(self.deep_layer_config, layer_idx=i+n_down_layers, compile=compile) for i in range(n_mid_layers) 
        ])

        self.up_layers = nn.ModuleList([
            create_gemma2DecoderLayer(self.byte_layer_config, layer_idx=i+n_down_layers+n_mid_layers, compile=compile) for i in range(n_up_layers)
        ])

        self.output_layer = nn.Linear(embedding_dim, vocab_size)

        self.separate_early_output = separate_early_output
        if separate_early_output:
            self.early_output_layer = deepcopy(self.output_layer) # We can try other things here, but I think this is the most straightforward.
        else:
            self.early_output_layer = self.output_layer

        if down_layer_gate is None:
            if GaterClass in independent_gater_classes:
                self.down_layer_gate = IndependentWrapperGater(GaterClass(embedding_dim, downsample_rate))
            else:
                self.down_layer_gate = GaterClass(embedding_dim, downsample_rate)
        else:
            self.down_layer_gate = down_layer_gate

        self._downsample_rate = downsample_rate

        if DownsampleRateEmbeddingClass is not None:
            self.downsample_rate_embedding = DownsampleRateEmbeddingClass(embedding_dim)
        else:
            self.downsample_rate_embedding = None

        self.downsampler = DownSamplerClass()
        self.upsampler = UpsamplerClass()
        self.rotary_emb = Gemma2RotaryEmbedding(config=self.byte_layer_config)

        # Pre-compute these for the flop counting.
        self.down_layers_parameters_count = count_parameters(self.down_layers)
        self.up_layers_parameters_count = count_parameters(self.up_layers)
        self.mid_layers_parameters_count = count_parameters(self.mid_layers)

        self.unembedding_parameters_count = count_parameters(self.output_layer)
        self.early_exit_parameters_count = count_parameters(self.early_output_layer)
        self.down_layer_gate_parameters_count = count_parameters(self.down_layer_gate)

        self.byte_level_parameters_count = (
            self.down_layers_parameters_count 
            + self.up_layers_parameters_count 
            + self.unembedding_parameters_count 
            + self.down_layer_gate_parameters_count 
            + self.early_exit_parameters_count
        )

    def forward(
            self, 
            input_ids: torch.Tensor, 
            position_ids: torch.Tensor=None,
            prescribed_down_gate_samples: torch.Tensor=None,
            down_gate_mask: torch.Tensor=None,
            cache_position: torch.Tensor=None,
            past_key_value=None,
            past_gate_samples=None, # TODO: implement
            use_cache=False,
            downsample_rate=None
        ) -> torch.Tensor:
        """
        prescribed_down_gate_samples: if provided, use these to gate the down layers.
        down_gate_mask: if provided, use this to mask the down layers.
        cache_position: if provided, use this to update the KV cache.
        """

        x = self.embedding(input_ids)

        y, x_early_exit, out = self.forward_backbone(
            x, 
            position_ids,
            prescribed_down_gate_samples,
            down_gate_mask,
            cache_position,
            past_key_value,
            past_gate_samples,
            use_cache,
            downsample_rate=downsample_rate
        )

        early_logits = self.early_output_layer(x_early_exit)
        early_logits = F.log_softmax(early_logits, dim=-1)

        # Map residual stream to logits
        logits = self.output_layer(y)
        logits = F.log_softmax(logits, dim=-1)

        out.update({
            "logits": logits,
            "early_logits": early_logits,
        })

        return out


    def forward_backbone(
            self,
            x,
            position_ids: torch.Tensor=None,
            prescribed_down_gate_samples: torch.Tensor=None,
            down_gate_mask: torch.Tensor=None,
            cache_position: torch.Tensor=None,
            past_key_value=None,
            past_gate_samples=None, # TODO: implement
            use_cache=False,
            downsample_rate=None
        ) -> torch.Tensor:
        """
        Maps embeddings through the residual stream.
        """
        batch_size, max_seq_len, _ = x.shape

        if position_ids is None:
            position_ids = torch.arange(max_seq_len, dtype=x.dtype).unsqueeze(0).expand(batch_size, -1).to(x.device)      
        
        # Position_ids are used for RoPE
        # cache_position is used for the cache.update() function which retrieves relevant kvs
        byte_cache_position, byte_attention_mask = get_gemma2_attention_mask(
            input_tensor=x,
            cache_position=cache_position,
            past_key_value=past_key_value,
            attn_implementation=self._attn_implementation
        )

        position_embeddings = self.rotary_emb(x, position_ids)

        if self.downsample_rate_embedding is not None:
            x = x + self.downsample_rate_embedding(downsample_rate, x.dtype, x.device)

        # Apply down layers to byte tokens        
        for layer in self.down_layers:
            x = layer(
                x,
                position_embeddings,
                attention_mask=byte_attention_mask,
                position_ids=position_ids,
                cache_position=byte_cache_position,
                past_key_value=past_key_value,
                use_cache=use_cache
            )[0]

        # Save x for computing the early exit logits.
        x_early_exit = x

        # Sample gating binary variables for each token.
        down_gate_logits, down_gate_probs, model_down_gate_samples = self.down_layer_gate(x, downsample_rate=downsample_rate)

        if prescribed_down_gate_samples is None:
            down_gate_samples = model_down_gate_samples
        elif down_gate_mask is None:
            down_gate_samples = prescribed_down_gate_samples.unsqueeze(-1)
        else:
            # Where down_gate_mask is True, use the prescribed down_gate_samples
            down_gate_samples = torch.where(down_gate_mask.unsqueeze(-1), prescribed_down_gate_samples.unsqueeze(-1), model_down_gate_samples)

        # Hack: ensure that we always gate on the first token:
        down_gate_samples, down_gate_probs, down_gate_logits = gate_first_and_last_tokens(down_gate_samples, down_gate_probs, down_gate_logits)

        # Merge the tokens into the next token where the gate is 1.
        down_gate_samples = down_gate_samples.squeeze(-1)
        x_downsampled, position_ids_downsampled, down_merge_dst = self.downsampler(x, position_ids, down_gate_samples)
        max_n_dst = x_downsampled.shape[1]

        # Apply mid layers to merged tokens and compute the deviation
        downsampled_cache_position, downsampled_attention_mask = get_gemma2_attention_mask(
            input_tensor=x_downsampled,
            cache_position=None,
            past_key_value=past_key_value,
            attn_implementation=self.attn_implementation
        )

        # print(f"{downsampled_cache_position.shape=} {downsampled_attention_mask.shape=}")
        # print(f"{downsampled_cache_position=}")

        y_downsampled = x_downsampled

        position_embeddings_downsampled = self.rotary_emb(x_downsampled, position_ids_downsampled)
        for layer in self.mid_layers:
            y_downsampled = layer(
                y_downsampled,
                position_embeddings_downsampled,
                attention_mask=downsampled_attention_mask,
                position_ids=position_ids_downsampled,
                cache_position=downsampled_cache_position,
                past_key_value=past_key_value,
                use_cache=use_cache
            )[0]
        
        deviation = y_downsampled - x_downsampled        

        # Add the upsampled deviation to the input to the middle layers
        upsampled_deviation, up_merge_dst = self.upsampler(deviation, down_gate_samples)
        y = x + upsampled_deviation

        # Apply up layers to byte tokens
        for layer in self.up_layers:
            y = layer(
                y,
                position_embeddings,
                attention_mask=byte_attention_mask,
                position_ids=position_ids,
                cache_position=byte_cache_position,
                past_key_value=past_key_value,
                use_cache=use_cache
            )[0]


        out = {
            "down_gate_probs": down_gate_probs.squeeze(-1),
            "down_gate_logits": down_gate_logits.squeeze(-1),
            "model_down_gate_samples": model_down_gate_samples.to(dtype=torch.long),
            "down_gate_samples": down_gate_samples.to(dtype=torch.long),
            "up_merge_dst": up_merge_dst[:, :, 0], # This dimension is repeated.
            "down_merge_dst": down_merge_dst[:, :, 0], # This dimension is repeated.
            "position_ids": position_ids,
            "past_key_value": past_key_value
        }

        return y, x_early_exit, out


    def get_num_flops(self, batch, out):
        """
        Estimate the number of flops for a forward/backward pass.
        """
        batch_size, sequence_length = batch.shape
        patch_sequence_length = out["down_gate_samples"].sum(dim=1).max()

        byte_level_flops = 6 * self.byte_level_parameters_count * batch_size * sequence_length
        mid_layer_flops = 6 * self.mid_layers_parameters_count * batch_size * patch_sequence_length

        total_flops = byte_level_flops + mid_layer_flops

        return total_flops

        
    @property
    def attn_implementation(self):
        return getattr(self, '_attn_implementation', None)
    
    @attn_implementation.setter
    def attn_implementation(self, attn_implementation: str):
        self._attn_implementation = attn_implementation
        print(f"setting {self._attn_implementation=}")
        # All layers contain references to these config objects:
        self.byte_layer_config._attn_implementation = attn_implementation
        self.deep_layer_config._attn_implementation = attn_implementation



def select_next_token_cross_entropy(logits, next_token_ids, next_token_loss_mask):
    current_token_logits = logits[:, :-1]
    next_token_cross_entropy = F.cross_entropy(current_token_logits.transpose(1, 2), next_token_ids, reduction="none") # Transpose as F.cross_entropy wants shape [batch, classes, ...]
    next_token_cross_entropy = next_token_cross_entropy * next_token_loss_mask
    next_token_cross_entropy = next_token_cross_entropy.to(dtype=torch.float32) # upcast to float32 before reducing
    return next_token_cross_entropy


def per_token_losses_backbone(
        batch, loss_mask, out, off_policy_gate_probs,
        discount_rate = 0.9, learn_gating=True, early_exit_advantage_estimate=True
    ):
    """
    The "backbone" of the loss computations. Computes per-token losses such as the next-token probabilities, the gating loss, the discounted rewards.
    """
    logits = out["logits"]
    early_logits = out["early_logits"]
    down_gate_samples = out["down_gate_samples"]
    on_policy_probs = out["down_gate_probs"]
    on_policy_logits = out["down_gate_logits"]

    # Compute autoregressive loss: log probability of next token. (for an early insertion of the lm head as well as the late lm head)
    batch_size, _ = batch.shape
    next_token_ids = batch[:, 1:]
    next_token_loss_mask = loss_mask[:, 1:]

    next_token_cross_entropy = select_next_token_cross_entropy(logits, next_token_ids, next_token_loss_mask)
    early_next_token_cross_entropy = select_next_token_cross_entropy(early_logits, next_token_ids, next_token_loss_mask)

    per_token_losses = {
        "next_token_cross_entropy": next_token_cross_entropy,
        "early_next_token_cross_entropy": early_next_token_cross_entropy,
        "next_token_loss_mask": next_token_loss_mask,
    }

    if learn_gating:
        # Compute gating loss: discounted log probabilities of following token(s).
        if early_exit_advantage_estimate:
            rewards = early_next_token_cross_entropy - next_token_cross_entropy
        else:
            rewards = - next_token_cross_entropy
    
        # Simple way to normalise rewards: compute the mean over the batch dimension (induction heads could cause dependence on the sequence index).
        mean_rewards = (rewards * next_token_loss_mask).sum(dim=0) / next_token_loss_mask.sum(dim=0) # Mask out the padding tokens as they have zero reward and would skew the mean.
        mean_rewards = mean_rewards.unsqueeze(0)
        rewards = (rewards - mean_rewards)*next_token_loss_mask
        discounted_rewards = discounted_rewards_torch(rewards, discount_rate)

        # actions: 0 = continue, 1 = gate
        action_log_probs = torch.stack([torch.zeros_like(on_policy_logits), on_policy_logits], dim=1) # As a sigmoid is equivalent to having one logit as 0.
        selected_action_cross_entropy = F.cross_entropy(action_log_probs, down_gate_samples, reduction="none")
        action_log_probs = action_log_probs.to(dtype=torch.float32) # upcast to float32 before reducing

        # likelihood_ratios [:, :, 1] gives the likelihood ratio for the action of gating.
        likelihood_ratios = torch.stack([
            (1 - on_policy_probs) / (1 - off_policy_gate_probs),
            on_policy_probs / off_policy_gate_probs
        ], dim=-1)
        likelihood_ratios = likelihood_ratios.detach() # Detach as we don't want to backpropagate through this.

        # Get the likelihood ratios for the selected actions for importance sampling.
        selected_action_likelihood_ratios = likelihood_ratios.gather(dim=-1, index=down_gate_samples.unsqueeze(-1))
        selected_action_likelihood_ratios = selected_action_likelihood_ratios.squeeze(-1)
        selected_action_likelihood_ratios = selected_action_likelihood_ratios.to(dtype=torch.float32) # upcast to float32 before reducing

        per_token_losses.update({
            "selected_action_cross_entropy": selected_action_cross_entropy,
            "selected_action_likelihood_ratios": selected_action_likelihood_ratios,
            "rewards": rewards,
            "discounted_rewards": discounted_rewards
        })

    return per_token_losses


def in_context_learning_score(next_token_ce, loss_mask, window_size=32, early_index=224, late_index=2016):
    """
    Compute the in-context-learning score a la https://transformer-circuits.pub/2022/in-context-learning-and-induction-heads/
    """
    # If all the sequences are too short, return 0.
    _, batch_max_seq_len = loss_mask.shape
    if batch_max_seq_len < late_index + window_size:
        return torch.tensor(0.0, device=next_token_ce.device)
    
    # We use the loss mask from the later tokens in the sequence to ignore sequences which are too short.
    # TODO: reweighting icl score across devices.
    delayed_loss_mask = loss_mask[:,late_index:late_index+window_size]
    in_context_learning_score = (delayed_loss_mask * (next_token_ce[:,late_index:late_index+window_size] - next_token_ce[:,early_index:early_index+window_size])).sum() / delayed_loss_mask.sum()
    return in_context_learning_score


def off_policy_flexible_training_step(
        model, 
        optimizer, 
        batch, 
        loss_mask, 
        scheduler=None, 
        accelerator=None, 
        learn_gating=True, 
        downsample_rate_target=0.25, 
        downsample_rate=None, 
        consistency_loss_weight=2., 
        discount_rate = 0.9, 
        relative_gating_loss_weight=1., 
        use_off_policy=True, 
        early_output_loss_weight=0.,
        early_exit_advantage_estimate=False, 
        do_backward_pass=True
    ):
    """
    Performs a single training step for the model. 

    batch: [batch_size, seq_len] torch Tensor of the token ids
    loss_mask: [batch_size, seq_len] torch Tensor of a mask which is 1 for tokens which should be used for loss computation (i.e. not padding).
    optimizer: torch.optim.Optimizer
    scheduler: torch.optim.lr_scheduler._LRScheduler
    accelerator: accelerate.Accelerator
    """

    batch_size, _ = batch.shape


    if use_off_policy:
        # For now: only consider Random gating
        off_policy_gate_probs = torch.ones_like(batch) * downsample_rate_target
        prescribed_down_gate_samples = torch.bernoulli(off_policy_gate_probs)
    else:
        prescribed_down_gate_samples = None

    with record_function("forward"):
        out_model = model(batch, prescribed_down_gate_samples=prescribed_down_gate_samples, downsample_rate=downsample_rate)
    
    on_policy_probs = out_model["down_gate_probs"]

    if not use_off_policy:
        off_policy_gate_probs = on_policy_probs

    with record_function("per_token_losses_backbone"):
        per_token_losses = per_token_losses_backbone(
            batch, 
            loss_mask, 
            out_model, 
            off_policy_gate_probs, 
            learn_gating=learn_gating, 
            early_exit_advantage_estimate=early_exit_advantage_estimate
        )

    next_token_cross_entropy = per_token_losses["next_token_cross_entropy"]
    early_next_token_cross_entropy = per_token_losses["early_next_token_cross_entropy"]
    next_token_loss_mask = per_token_losses["next_token_loss_mask"]

    # Compute the number of non-padding bytes across all devices for proper scaling of loss when using multi-gpu and gradient accumulation
    all_bytes = accelerator.reduce(torch.tensor(batch.numel(), device=accelerator.device), reduction="sum").item()
    non_padding_bytes_batch = loss_mask.sum()
    non_padding_bytes = accelerator.reduce(non_padding_bytes_batch, reduction="sum").item()

    # For logging: compute the in-context-learning score a la https://transformer-circuits.pub/2022/in-context-learning-and-induction-heads/
    icl_score = in_context_learning_score(next_token_cross_entropy, next_token_loss_mask)

    late_ar_loss = (next_token_cross_entropy).sum() / non_padding_bytes_batch
    early_ar_loss = (early_next_token_cross_entropy).sum() / non_padding_bytes_batch

    ar_loss = (1 - early_output_loss_weight) * late_ar_loss + early_output_loss_weight * early_ar_loss
    
    true_downsample_rate = on_policy_probs.mean()

    if learn_gating:
        selected_action_cross_entropy = per_token_losses["selected_action_cross_entropy"]
        selected_action_likelihood_ratios = per_token_losses["selected_action_likelihood_ratios"]
        discounted_rewards = per_token_losses["discounted_rewards"]

        # For logging: compute the selected action cross entropy.
        mean_selected_action_cross_entropy = selected_action_cross_entropy.mean()
        
        # Compute the gating loss (such that calling backward() computes the policy gradient).
        # The fact that we can just ignore masked values means that the loss is properly scaled by the number of non-padding bytes.
        discounted_rewards = torch.cat([discounted_rewards, torch.zeros(batch_size, 1, device=discounted_rewards.device)], dim=-1) # Pad the last reward as zero (the only corresponding action is forced as gating).
        selected_action_log_probs = -selected_action_cross_entropy
        gating_loss = - (selected_action_likelihood_ratios * discounted_rewards * selected_action_log_probs).mean() # Negative as we want to maximise the reward.
        gating_loss = relative_gating_loss_weight * gating_loss

        # Hacky additional consistency loss: make the downsampling rate match the training gating.
        down_gate_rate_loss = consistency_loss_weight*(downsample_rate_target - true_downsample_rate) **2

        total_loss = ar_loss + gating_loss + down_gate_rate_loss
    else:
        # For logging purposes set these to zero.
        gating_loss = torch.tensor(0.0, device=accelerator.device)
        down_gate_rate_loss = torch.tensor(0.0, device=accelerator.device) 
        mean_selected_action_cross_entropy = torch.tensor(0.0, device=accelerator.device)
        
        # The only loss is the autoregressive loss.
        total_loss = ar_loss

    with record_function("backward"):
        # Optimizer step
        if do_backward_pass:
            if accelerator is None:
                total_loss.backward()
                pre_clip_grad_norm = torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            else:
                accelerator.backward(total_loss)
                pre_clip_grad_norm = accelerator.clip_grad_norm_(model.parameters(), max_norm=1.0)
            
            optimizer.step()

            if scheduler is not None:
                scheduler.step()

            optimizer.zero_grad()

        else:
            pre_clip_grad_norm = torch.tensor(0.0, device=accelerator.device)

    out_raw = {
        "all_bytes": all_bytes,
        "non_padding_bytes": non_padding_bytes,
    }

    out_avg = {
        "gating_loss": gating_loss,
        "true_downsample_rate": true_downsample_rate,
        "rate_consistency_loss": down_gate_rate_loss,
        "total_loss": total_loss,
        "ar_loss": ar_loss,
        "late_ar_loss": late_ar_loss,
        "early_ar_loss": early_ar_loss,
        "mean_selected_action_ce": mean_selected_action_cross_entropy,
        "pre_clip_grad_norm": pre_clip_grad_norm,
        "in_context_learning_score": icl_score
    }

    if accelerator is None or accelerator.num_processes == 1:
        flops = model.get_num_flops(batch, out_model)
    else:
        flops = model.module.get_num_flops(batch, out_model)
        
    out_sum = {
        "flops": flops,
    }

    for k, v in out_avg.items():
        try:
            out_avg[k] = accelerator.reduce(v, reduction="mean").item()
        except:
            print(f"error reducing rank:{accelerator.process_index} {k=} {v.shape=} {v.device=}")

    for k, v in out_sum.items():
        out_sum[k] = accelerator.reduce(v, reduction="sum").item()

    out = {**out_raw,**out_avg, **out_sum}

    return out


class CheckpointCondition:
    """
    A condition for when to checkpoint or stop the training loop.
    """
    def __call__(self, all_bytes_elapsed, non_padding_bytes_elapsed, flops_elapsed, effective_batches_elapsed):
        """
        Default implementation: only return True once, the first time when the condition is met.
        """
        raise NotImplementedError()


class BatchLimitCondition(CheckpointCondition):
    def __init__(self, effective_batch_limit):
        self.effective_batch_limit = effective_batch_limit
        
    def __call__(self, all_bytes_elapsed, non_padding_bytes_elapsed, flops_elapsed, effective_batches_elapsed):
        return effective_batches_elapsed >= self.effective_batch_limit


def text_to_tensor(batch, tokenizer, max_seq_length, device):
    batch_text = batch["text"]
    tokenized = tokenizer(batch_text, return_tensors="pt", padding=True, add_special_tokens=True)
    loss_mask = tokenized["attention_mask"]
    batch = tokenized["input_ids"]

    # Truncate to maximum length of 4096 to save GPU memory.
    batch = batch[:, :max_seq_length]  
    loss_mask = loss_mask[:, :max_seq_length]
    batch = batch.to(device)
    loss_mask = loss_mask.to(device)

    return batch, loss_mask


def aggregate_val_metrics(val_metrics):
    """
    Aggregate the validation metrics batches.
    """
    val_keys = [
        "gating_loss", "true_downsample_rate", "rate_consistency_loss", "total_loss", 
        "mean_selected_action_ce", "in_context_learning_score", 
        "ar_loss", "late_ar_loss", "early_ar_loss"
    ]
    aggregated_val_metrics = {}

    for k in val_keys:
        k_val = "val_" + k
        aggregated_val_metrics[k_val] = sum([batch[k] for batch in val_metrics]) / len(val_metrics)
    
    return aggregated_val_metrics


def flexible_training_loop_warm_start_accelerate(
        model, 
        optimizer, 
        lr_scheduler, 
        train_dataloader, 
        val_dataloader,
        accelerator,
        tokenizer,
        downsample_rate_target=0.25, 
        downsample_rate_schedule=None,
        num_epochs=1, 
        warm_start_steps = None, 
        max_seq_length = 1024, 
        step_print_every = 10,
        validate_every = 100,
        stop_condition: CheckpointCondition = None,
        all_bytes_elapsed = 0,
        non_padding_bytes_elapsed = 0,
        flops_elapsed = 0,
        effective_batches_elapsed = 0,
        **training_step_kwargs
    ):
    """
    This is the main training loop, compatible with the accelerate and wandb libraries. 
    The wrapping of model, dataloader, optimizer should be done before passing to this function. 


    """

    device = accelerator.device
    model = model.to(device)

    gpu_TFLOPS = lookup_gpu_TFLOPS()

    starting_step_count = effective_batches_elapsed * accelerator.gradient_accumulation_steps
    print(f"Starting step count: {starting_step_count}")

    if downsample_rate_schedule is None:
        downsample_rate_schedule = DefaultDownsampleRateScheduler(downsample_rate_target)

    # Training loop
    for epoch in range(num_epochs):

        for step_count, batch in enumerate(train_dataloader):
            step_count += starting_step_count

            # Validation phase
            if effective_batches_elapsed % validate_every == 0 and step_count % accelerator.gradient_accumulation_steps == 0:
                
                val_downsample_rate, val_downsample_rate_target = downsample_rate_schedule.val_step()

                model.eval()
                with torch.no_grad():
                    print(f"Validating at step {step_count}")
                    val_metrics = []
                    for val_batch in val_dataloader:
                        val_batch, loss_mask = text_to_tensor(val_batch, tokenizer, max_seq_length, device)
                        val_loss_dict = off_policy_flexible_training_step(
                            model, 
                            optimizer, 
                            val_batch, 
                            loss_mask, 
                            lr_scheduler, 
                            accelerator, 
                            use_off_policy=False,
                            do_backward_pass=False,
                            downsample_rate=val_downsample_rate,
                            downsample_rate_target=val_downsample_rate_target,
                            **training_step_kwargs
                        )
                        val_metrics.append(val_loss_dict)

                    val_loss_dict = aggregate_val_metrics(val_metrics)
                    val_loss_dict.update({
                        "val_downsample_rate": val_downsample_rate,
                        "val_downsample_rate_target": val_downsample_rate_target,
                    })
                    accelerator.log(val_loss_dict, step=step_count)
            
            if step_count % accelerator.gradient_accumulation_steps == 0:
                downsample_rate, downsample_rate_target = downsample_rate_schedule.step()

            #Training phase
            model.train()
            with accelerator.accumulate(model):

                start_time = time.time()

                if warm_start_steps is not None and step_count < warm_start_steps:
                    use_off_policy = True
                else:
                    use_off_policy = False

                batch, loss_mask = text_to_tensor(batch, tokenizer, max_seq_length, device)

                loss_dict = off_policy_flexible_training_step(
                    model, 
                    optimizer, 
                    batch, 
                    loss_mask, 
                    lr_scheduler, 
                    accelerator, 
                    use_off_policy=use_off_policy,
                    downsample_rate=downsample_rate,
                    downsample_rate_target=downsample_rate_target,
                    **training_step_kwargs
                )

                batch_flops = loss_dict["flops"]

                all_bytes_elapsed += loss_dict["all_bytes"]
                non_padding_bytes_elapsed += loss_dict["non_padding_bytes"]
                flops_elapsed += batch_flops

                if step_count % accelerator.gradient_accumulation_steps == 0:
                    effective_batches_elapsed += 1

                batch_wallclock_time = time.time() - start_time

                model_flops_utilization = batch_flops / (batch_wallclock_time * gpu_TFLOPS * 1e12)

                loss_dict.update({
                    "downsample_rate": downsample_rate,
                    "downsample_rate_target": downsample_rate_target,
                    "all_bytes_elapsed": all_bytes_elapsed,
                    "non_padding_bytes_elapsed": non_padding_bytes_elapsed,
                    "flops_elapsed": flops_elapsed,
                    "learning_rate": lr_scheduler.get_last_lr()[0],
                    "batch_wallclock_time": batch_wallclock_time,
                    "model_flops_utilization": model_flops_utilization
                })

                accelerator.log(loss_dict, step=step_count)

                if step_count % step_print_every == 0 and accelerator.is_main_process:
                    print(f"{accelerator.device}: Bytes elapsed: {non_padding_bytes_elapsed/1e6:.1f}M ar train ar loss: {loss_dict['ar_loss']} nats/token batch time: {batch_wallclock_time:.2f}s model flops utilization: {model_flops_utilization:.2%}")

                if (
                    stop_condition is not None and 
                    stop_condition(all_bytes_elapsed, non_padding_bytes_elapsed, flops_elapsed, effective_batches_elapsed) and 
                    (step_count + 1) % accelerator.gradient_accumulation_steps == 0 # ensure we only break at the end of an effective batch
                ):
                    break

                exit()

    elapsed_vals = {
        "all_bytes_elapsed": all_bytes_elapsed,
        "non_padding_bytes_elapsed": non_padding_bytes_elapsed,
        "flops_elapsed": flops_elapsed,
        "effective_batches_elapsed": effective_batches_elapsed
    }

    return elapsed_vals



def save_checkpoint(output_dir, accelerator, elapsed_vals):
    # ensure that the scheduler is registered for checkpointing
    # elapsed_vals = {
    #     "all_bytes_elapsed": all_bytes_elapsed,
    #     "non_padding_bytes_elapsed": non_padding_bytes_elapsed,
    #     "flops_elapsed": flops_elapsed,
    #     "effective_batches_elapsed": effective_batches_elapsed
    # }
    
    # save the model, optimizer, scheduler, and the run state
    accelerator.save_state(output_dir)

    with open(os.path.join(output_dir, "elapsed_vals.json"), "w") as f:
        json.dump(elapsed_vals, f)


def load_checkpoint(input_dir, accelerator, dataloader, effective_batch_size, batch_size):
    # load the model, optimizer, scheduler, and the run state
    accelerator.load_state(input_dir)

    with open(os.path.join(input_dir, "elapsed_vals.json"), "r") as f:
        elapsed_vals = json.load(f)

    effective_batches_elapsed = elapsed_vals["effective_batches_elapsed"]

    step_batch_size = accelerator.num_processes * batch_size

    steps_per_effective_batch = effective_batch_size // step_batch_size # = accelerator.grad_accumulation_steps

    print(f"{steps_per_effective_batch=} {effective_batch_size=} {batch_size=}")
    assert effective_batch_size % step_batch_size == 0, f"{effective_batch_size=} must be a multiple of the {step_batch_size=}"

    # accelerator.skip_first_batches actually skips steps, not batches or effective batches.
    steps_to_skip = effective_batches_elapsed * steps_per_effective_batch
    print(f"Skipping {steps_to_skip} batches")
    skipped_dataloader = accelerator.skip_first_batches(dataloader, steps_to_skip)

    return skipped_dataloader, elapsed_vals
