_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
            "3":
                - 16
                - 23
                - 55
                - 61
            "4": 3.11.12
            "5": 0.19.11
            "6": 4.51.3
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
DownSamplerClass:
    value: SelectTokenDownsampler
GaterClass:
    value: SequentiallyDependentLinearGater
batch_limit:
    value: 40000
batch_print_every:
    value: 100
batch_size:
    value: 16
downsample_rate:
    value: 0.25
early_output_loss_weight:
    value: 0.2
embedding_dim:
    value: 1024
learn_gating:
    value: false
learning_rate:
    value: 0.0015
max_seq_length:
    value: 4096
n_down_layers:
    value: 3
n_mid_layers:
    value: 18
n_up_layers:
    value: 3
num_epochs:
    value: 1
num_heads:
    value: 16
seed:
    value: 42
sliding_window:
    value: 64
vocab_size:
    value: 256
warm_start_steps:
    value: null
warmup_steps:
    value: 18310.546875
